name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
